version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 572954863672.dkr.ecr.ap-south-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t $IMAGE_REPO_NAME .
      - docker tag $IMAGE_REPO_NAME 572954863672.dkr.ecr.ap-south-1.amazonaws.com/$IMAGE_REPO_NAME     
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 572954863672.dkr.ecr.ap-south-1.amazonaws.com/$IMAGE_REPO_NAME
      - echo write definitions file...
      - printf '[{"name":"mautic-pipeline","imageUri":"%s"}]' 572954863672.dkr.ecr.ap-south-1.amazonaws.com/$IMAGE_REPO_NAME > imagedefinitions.json
artifacts:
  files: imagedefinitions.json